# Generated by Django 4.1.7 on 2023-03-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('presence', models.BooleanField(db_column='Presence')),
                ('priority', models.IntegerField(db_column='Priority')),
                ('state', models.SmallIntegerField(db_column='State')),
                ('createdate', models.DateTimeField(db_column='CreateDate')),
                ('updatedate', models.DateTimeField(db_column='UpdateDate')),
                ('eventid', models.ForeignKey(db_column='EventId', on_delete=django.db.models.deletion.DO_NOTHING, to='event.event')),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'db_table': 'Inscription',
            },
        ),
    ]
