# Generated by Django 4.1.3 on 2023-03-22 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showid', models.BigIntegerField(blank=True, db_column='ShowId', null=True)),
                ('cityid', models.CharField(blank=True, db_column='CityId', max_length=36, null=True)),
                ('local', models.CharField(blank=True, db_column='Local', max_length=300, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=400, null=True)),
                ('partnercompany', models.CharField(blank=True, db_column='PartnerCompany', max_length=150, null=True)),
                ('presentationdate', models.DateTimeField(blank=True, db_column='PresentationDate', null=True)),
                ('schedule', models.DateTimeField(blank=True, db_column='Schedule', null=True)),
                ('enrollstartat', models.DateTimeField(blank=True, db_column='EnrollStartAt', null=True)),
                ('enrollendat', models.DateTimeField(blank=True, db_column='EnrollEndAt', null=True)),
                ('ticketquantity', models.IntegerField(blank=True, db_column='TicketQuantity', null=True)),
                ('ticketavailable', models.IntegerField(blank=True, db_column='TicketAvailable', null=True)),
                ('ticketbymember', models.IntegerField(blank=True, db_column='TicketByMember', null=True)),
                ('queuesize', models.IntegerField(blank=True, db_column='QueueSize', null=True)),
                ('queueremaining', models.IntegerField(blank=True, db_column='QueueRemaining', null=True)),
                ('state', models.SmallIntegerField(blank=True, db_column='State', null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
            ],
            options={
                'db_table': '_EventHistory',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('state', models.SmallIntegerField(db_column='State')),
                ('createdate', models.DateTimeField(db_column='CreateDate')),
                ('updatedate', models.DateTimeField(db_column='UpdateDate')),
            ],
        ),
        migrations.CreateModel(
            name='Showtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('state', models.SmallIntegerField(db_column='State')),
                ('createdate', models.DateTimeField(db_column='CreateDate')),
                ('updatedate', models.DateTimeField(db_column='UpdateDate')),
            ],
        ),
        migrations.CreateModel(
            name='Genreshowtype',
            fields=[
                ('genreid', models.OneToOneField(db_column='GenreId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='event.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('synopsis', models.CharField(db_column='Synopsis', max_length=1500)),
                ('classification', models.CharField(blank=True, db_column='Classification', max_length=150, null=True)),
                ('duration', models.IntegerField(db_column='Duration')),
                ('postscript', models.CharField(blank=True, db_column='PostScript', max_length=250, null=True)),
                ('video', models.CharField(blank=True, db_column='Video', max_length=150, null=True)),
                ('highlight', models.SmallIntegerField(blank=True, db_column='HighLight', null=True)),
                ('state', models.SmallIntegerField(db_column='State')),
                ('createdate', models.DateTimeField(db_column='CreateDate')),
                ('updatedate', models.DateTimeField(db_column='UpdateDate')),
                ('genreid', models.ForeignKey(db_column='GenreId', on_delete=django.db.models.deletion.DO_NOTHING, to='event.genre')),
                ('showtypeid', models.ForeignKey(db_column='ShowTypeId', on_delete=django.db.models.deletion.DO_NOTHING, to='event.showtype')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=300)),
                ('length', models.IntegerField(db_column='Length')),
                ('path', models.TextField(db_column='Path')),
                ('thumbnailpath', models.TextField(blank=True, db_column='ThumbnailPath', null=True)),
                ('extension', models.TextField(blank=True, db_column='Extension', null=True)),
                ('state', models.SmallIntegerField(db_column='State')),
                ('createdate', models.DateTimeField(db_column='CreateDate')),
                ('updatedate', models.DateTimeField(db_column='UpdateDate')),
                ('showid', models.ForeignKey(db_column='ShowId', on_delete=django.db.models.deletion.DO_NOTHING, to='event.show')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(db_column='Local', max_length=300)),
                ('address', models.CharField(db_column='Address', max_length=400)),
                ('partnercompany', models.CharField(blank=True, db_column='PartnerCompany', max_length=150, null=True)),
                ('presentationdate', models.DateTimeField(db_column='PresentationDate')),
                ('schedule', models.DateTimeField(db_column='Schedule')),
                ('enrollstartat', models.DateTimeField(db_column='EnrollStartAt')),
                ('enrollendat', models.DateTimeField(db_column='EnrollEndAt')),
                ('ticketquantity', models.IntegerField(db_column='TicketQuantity')),
                ('ticketavailable', models.IntegerField(db_column='TicketAvailable')),
                ('ticketbymember', models.IntegerField(db_column='TicketByMember')),
                ('queuesize', models.IntegerField(db_column='QueueSize')),
                ('queueremaining', models.IntegerField(db_column='QueueRemaining')),
                ('state', models.SmallIntegerField(db_column='State')),
                ('createdate', models.DateTimeField(db_column='CreateDate')),
                ('updatedate', models.DateTimeField(db_column='UpdateDate')),
                ('cityid', models.ForeignKey(db_column='CityId', on_delete=django.db.models.deletion.DO_NOTHING, to='general.city')),
                ('showid', models.ForeignKey(db_column='ShowId', on_delete=django.db.models.deletion.DO_NOTHING, to='event.show')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_column='Content', max_length=500)),
                ('state', models.SmallIntegerField(db_column='State')),
                ('createdate', models.DateTimeField(db_column='CreateDate')),
                ('updatedate', models.DateTimeField(db_column='UpdateDate')),
                ('showid', models.ForeignKey(db_column='ShowId', on_delete=django.db.models.deletion.DO_NOTHING, to='event.show')),
            ],
        ),
    ]
