# Generated by Django 4.1.3 on 2023-03-27 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genreshowtype',
            name='showtypeid',
            field=models.ForeignKey(db_column='ShowTypeId', on_delete=django.db.models.deletion.DO_NOTHING, to='event.showtype'),
        ),
        migrations.AlterUniqueTogether(
            name='genreshowtype',
            unique_together={('genreid', 'showtypeid')},
        ),
    ]
