# Generated by Django 4.1.7 on 2023-03-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('state', models.SmallIntegerField(db_column='State')),
                ('createdate', models.DateTimeField(db_column='CreateDate')),
                ('updatedate', models.DateTimeField(db_column='UpdateDate')),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Logactivity',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Date')),
                ('message', models.CharField(blank=True, db_column='Message', max_length=4000, null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=30, null=True)),
                ('browser', models.CharField(blank=True, db_column='Browser', max_length=250, null=True)),
                ('hostname', models.CharField(blank=True, db_column='HostName', max_length=500, null=True)),
                ('userhostaddress', models.CharField(blank=True, db_column='UserHostAddress', max_length=500, null=True)),
                ('querystring', models.CharField(blank=True, db_column='QueryString', max_length=500, null=True)),
                ('filepath', models.CharField(blank=True, db_column='FilePath', max_length=250, null=True)),
                ('identity', models.CharField(blank=True, db_column='Identity', max_length=250, null=True)),
                ('plataform', models.CharField(blank=True, db_column='Plataform', max_length=250, null=True)),
                ('mobiledevicemodel', models.CharField(blank=True, db_column='MobileDeviceModel', max_length=250, null=True)),
            ],
            options={
                'db_table': 'LogActivity',
            },
        ),
        migrations.CreateModel(
            name='Logerror',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Date')),
                ('level', models.CharField(blank=True, db_column='Level', max_length=50, null=True)),
                ('logger', models.CharField(blank=True, db_column='Logger', max_length=255, null=True)),
                ('message', models.CharField(blank=True, db_column='Message', max_length=4000, null=True)),
                ('exception', models.CharField(blank=True, db_column='Exception', max_length=8000, null=True)),
                ('browser', models.CharField(blank=True, db_column='Browser', max_length=250, null=True)),
                ('hostname', models.CharField(blank=True, db_column='HostName', max_length=500, null=True)),
                ('userhostaddress', models.CharField(blank=True, db_column='UserHostAddress', max_length=500, null=True)),
                ('querystring', models.CharField(blank=True, db_column='QueryString', max_length=500, null=True)),
                ('filepath', models.CharField(blank=True, db_column='FilePath', max_length=250, null=True)),
                ('identity', models.CharField(blank=True, db_column='Identity', max_length=250, null=True)),
                ('plataform', models.CharField(blank=True, db_column='Plataform', max_length=250, null=True)),
                ('mobiledevicemodel', models.CharField(blank=True, db_column='MobileDeviceModel', max_length=250, null=True)),
            ],
            options={
                'db_table': 'LogError',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('key', models.CharField(db_column='Key', max_length=100)),
                ('value', models.CharField(blank=True, db_column='Value', max_length=250, null=True)),
                ('description', models.CharField(db_column='Description', max_length=250)),
                ('state', models.SmallIntegerField(db_column='State')),
                ('createdate', models.DateTimeField(db_column='CreateDate')),
                ('updatedate', models.DateTimeField(db_column='UpdateDate')),
            ],
            options={
                'db_table': 'Parameter',
            },
        ),
    ]
