# Generated by Django 4.1.3 on 2023-03-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.SlugField(db_column='Id', max_length=36, primary_key=True, serialize=False)),
                ('entityid', models.CharField(db_column='EntityId', max_length=36)),
                ('login', models.CharField(blank=True, db_column='Login', max_length=500, null=True)),
                ('password', models.CharField(db_column='password', max_length=128)),
                ('crypt', models.CharField(db_column='Crypt', max_length=128)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=200, null=True)),
                ('rf', models.CharField(blank=True, db_column='RF', max_length=25, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('tel', models.TextField(blank=True, db_column='Tel', null=True)),
                ('isadmin', models.BooleanField(db_column='IsAdmin', default=False)),
                ('eventduedate', models.DateTimeField(blank=True, db_column='EventDueDate', null=True)),
                ('punishmentduedate', models.DateTimeField(blank=True, db_column='PunishmentDueDate', null=True)),
                ('state', models.SmallIntegerField(blank=True, db_column='State', null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
            ],
        ),
    ]
