# Generated by Django 4.1.7 on 2023-03-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(db_column='Id', max_length=36, primary_key=True, serialize=False)),
                ('entityid', models.CharField(db_column='EntityId', max_length=36)),
                ('login', models.CharField(blank=True, db_column='Login', max_length=500, null=True)),
                ('crypt', models.CharField(db_column='Crypt', max_length=128)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=200, null=True)),
                ('rf', models.CharField(blank=True, db_column='RF', max_length=25, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('tel', models.TextField(blank=True, db_column='Tel', null=True)),
                ('isadmin', models.BooleanField(db_column='IsAdmin')),
                ('eventduedate', models.DateTimeField(blank=True, db_column='EventDueDate', null=True)),
                ('punishmentduedate', models.DateTimeField(blank=True, db_column='PunishmentDueDate', null=True)),
                ('state', models.SmallIntegerField(db_column='State')),
                ('createdate', models.DateTimeField(db_column='CreateDate')),
                ('updatedate', models.DateTimeField(db_column='UpdateDate')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
